### ISSUE TITLE
using lsusb with php exec()

### ISSUE THREAD

**Issue by danm** [jlhonora/lsusb#5]
Hey there,
nice script,
I'm trying to execute it from php using exec() but the results are extremely limited:

Bus 010 Device 001: ID 05ac:8007 Apple Inc. XHCI Root Hub USB 2.0 Simulation 
Bus 010 Device 001: ID 05ac:8007 Apple Inc. XHCI Root Hub USB 2.0 Simulation 
Bus 026 Device 001: ID 05ac:8006 Apple Inc. EHCI Root Hub Simulation 

compared to when I run the script from the command line.

Bus 026 Device 002: ID 8087:0024 Intel Corporation Hub 
Bus 026 Device 003: ID 05ac:8510 Apple Inc. FaceTime HD Camera (Built-in)  Serial: CC2C9C098NDN9KE0
Bus 029 Device 002: ID 8087:0024 Intel Corporation Hub 
Bus 029 Device 007: ID 05ac:12a8 Apple Inc. iPhone  Serial: a816c526c6a06f4ef0ce28128bb9e44d454f39ff
Bus 029 Device 003: ID 0424:2512 SMSC Hub 
Bus 029 Device 005: ID 0a5c:4500 Broadcom Corp. BRCM20702 Hub 

Is there a user permission needed to be able to retrieve the entire log of all devices using system_profiler?

Cheers

**Comment by johnfreed** [comment]
I just saw this thread for the first time. I recall that in testing, several lsusb options required root/wheel, so this could be a reflection of that. Note that system_profiler is in sbin, not bin. So basically, an Apache web server isn't going to have access to much of the inner workings of the system. I'm marking this as closed.

**Comment by jlhonora** [comment]
Thanks for the explanation and for taking action :)

Sent from a mobile device

On Feb 5, 2017 11:32 AM, "John Freed" <notifications@github.com> wrote:

I just saw this thread for the first time. I recall that in testing,
several lsusb options required root/wheel, so this could be a reflection of
that. Note that system_profiler is in sbin, not bin. So basically, an
Apache web server isn't going to have access to much of the inner workings
of the system. I'd mark this as closed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jlhonora/lsusb/issues/5#issuecomment-277542884>, or mute
the thread
